In [1]:
import numpy as np
import time 
import sys 

arr = np.array([1,2,3,4,5,6]) # we can pass any array like structure (list,tuple etc) to create ndarray
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [2]:
print(np.__version__)

1.23.5


In [6]:
arr1 = np.array(42)
print(arr1)
print(type(arr1))

42
<class 'numpy.ndarray'>


In [13]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print('Dimension of the array:',arr2.ndim) #Dimension of the array
print()

[[1 2 3]
 [4 5 6]]
Dimension of the array: 2


In [3]:
#Numpy array is faster in processing
size = 1000000
lst1 = range(size)
lst2 = range(size)

array1 = np.arange(size)
array2 = np.arange(size)

start = time.time()
list_result = [(x+y) for x,y in zip(lst1,lst2)]
print('Pyhton list took:',(time.time()-start)*1000)
start = time.time()
array_result = array1 + array2
print('Numpy took:',(time.time()-start)*1000)


Pyhton list took: 59.625864028930664
Numpy took: 2.335071563720703


In [10]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

add = a1+a2; print(add)
sub = a1-a2; print(sub)
mul = a1*a2; print(mul)
div = a1/a2; print(div)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [22]:
#Byte size of element in array

v = np.array([[1,2],[3,4],[5,6]], dtype = np.int64)
print(v.itemsize)
print(v.dtype)
print(v)

8
int64
[[1 2]
 [3 4]
 [5 6]]


In [23]:
v.size #Total number of elements

6

In [24]:
v.shape # Dimensions of the array ie.. 3 rows and 2 columns

(3, 2)

In [25]:
np.zeros( (3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [28]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [33]:
np.linspace(1,6,7)

array([1.        , 1.83333333, 2.66666667, 3.5       , 4.33333333,
       5.16666667, 6.        ])

In [34]:
v.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
v.ravel() #makes the array one dimensional

array([1, 2, 3, 4, 5, 6])

In [36]:
v # ravel and reshape do not alter the original array but creates a new one

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
print(v.min())
print(v.max())

1
6


In [38]:
v.sum()

21

In [39]:
v.sum(axis=0) # adds each column value ie.. vertical axis

array([ 9, 12])

In [40]:
v.sum(axis=1) #adds each row ie.. horizontal axis

array([ 3,  7, 11])

In [42]:
np.sqrt(v) # square root of each element in the array

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [43]:
np.std(v) #std means standard deviation

1.707825127659933

In [44]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a.dot(b) #matrix multiplication

array([[19, 22],
       [43, 50]])

In [45]:
c = np.array([1,2,3,4,5,6])
c[1:4]

array([2, 3, 4])

In [46]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
d[1,2] #[a,b] means row,column and row&column starts at 0th

6

In [48]:
d[0:2,2] #goes through 0th and 1st row and prints the 2nd element

array([3, 6])

In [49]:
d[-1,1:3]

array([8, 9])

In [50]:
d[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [53]:
for row in d:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [54]:
for element in d.flat:
    print(element)

1
2
3
4
5
6
7
8
9


In [58]:
arr_1 = np.arange(6).reshape(3,2)
arr_2 = np.arange(6,12).reshape(3,2)

np.vstack((arr_1,arr_2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [59]:
np.hstack((arr_1,arr_2))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [60]:
arr_3 = np.arange(30).reshape(2,15)
arr_3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [61]:
np.hsplit(arr_3,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [65]:
np.vsplit(arr_3,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [67]:
a_arr = np.arange(12).reshape(3,4)
a_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
b_arr = a_arr > 4 
b_arr

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [71]:
a_arr[b_arr]

array([ 5,  6,  7,  8,  9, 10, 11])

In [77]:
a_arr[b_arr] = 69
a_arr

array([[ 0,  1,  2,  3],
       [ 4, 69, 69, 69],
       [69, 69, 69, 69]])

In [91]:
m = np.arange(12).reshape(3,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
for cell in m.flatten(): #flatten() and .flat do the same thing
    print(cell) 

0
1
2
3
4
5
6
7
8
9
10
11


In [85]:
for x in np.nditer(m,order = 'C'): # going row by bow and printing each element (C order)
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [86]:
for x in np.nditer(m,order = 'F'): # going column by column and printing each element (Fortran order)
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [88]:
for x in np.nditer(m,order = 'F',flags = ['external_loop']): 
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [92]:
for x in np.nditer(m , op_flags = ['readwrite']):
    x[...] = x*x

print(m)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [93]:
n = np.arange(3,15,4).reshape(3,1)
n

array([[ 3],
       [ 7],
       [11]])

In [94]:
for x,y in np.nditer([m,n]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
